---
title: Gerrymandering Metrics
format: typst
---

### 2024 Election Results and the 2024 District Map

```{r}
library(tidyverse)

d <- nice |>
  group_by(CDDIST) |>
  summarise(dem = sum(CNGDEM01, na.rm = TRUE),
            rep = sum(CNGREP01, na.rm = TRUE)) |>
  mutate(share = dem / (dem + rep))

mean_median <- mean(d$share) - median(d$share)

eff_gapyas <- (sum(ifelse(d$rep > d$dem, d$rep - d$dem, d$rep)) -
       sum(ifelse(d$dem > d$rep, d$dem - d$rep, d$dem))) /
      sum(d$dem + d$rep)

mean_median
eff_gapyas
```

The mean–median score is -0.01163046 which shows only a slight tilt against the Democrats. The efficiency gap was 0.1528829 points which meant a little bit of a Republican advantage in the  district map.

### 2024 Election Results and the proposed 2025 District Map

```{r}
library(sf)
library(dplyr)

oldie_votes <- read.csv("data/state_g24_sov_data_by_srprec.csv")

oldie_shapes <- st_read("data/shapefiles/srprec_state_g24_v01_shp/srprec_state_g24_v01_shp.shp") |>
  st_transform(3310) |>
  st_set_precision(1) |>
  st_make_valid() |>
  st_collection_extract("POLYGON")

oldie_geo <- oldie_shapes |> left_join(oldie_votes, by = "SRPREC")

newyas_map <- st_read("data/shapefiles/ab604.csv") |>
  st_transform(3310)

newyas_results <- st_interpolate_aw(oldie_geo, newyas_map, extensive = TRUE)
write.csv(newyas_results, "data/ab604.csv", row.names = FALSE)

ny <- read.csv("data/ab604.csv")

mm <- mean(ny$DEM - ny$REP) - median(ny$DEM - ny$REP)

waste <- function(a,b){
  tot <- a+b
  win <- a>b
  cbind(ifelse(win, a-tot/2, a),
        ifelse(win, b, b-tot/2))
}

w <- waste(ny$DEM, ny$REP)
eg <- (sum(w[,1]) - sum(w[,2])) / sum(ny$DEM + ny$REP)

mm
eg
```